---
- name: Download SurrealDB
  get_url:
    url: "https://github.com/surrealdb/surrealdb/releases/download/v{{ surrealdb_version }}/surreal-{{ surrealdb_version }}.linux-amd64.tar.gz"
    dest: /tmp/surreal.tar.gz

- name: Extract SurrealDB
  unarchive:
    src: /tmp/surreal.tar.gz
    dest: /usr/local/bin
    remote_src: yes

- name: Create systemd service
  template:
    src: templates/surrealdb.service.j2
    dest: /etc/systemd/system/surrealdb.service

- name: Start SurrealDB service
  systemd:
    name: surrealdb
    state: started
    enabled: yes
